name: Main Workflow
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-20.04
    steps: 
      - name: Print to console
        run: echo heloo gh actions!
      - name: Print a few lines
        run: |
          echo First Line
          echo Second line!
